import Navbar from "@/app/components/layout/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full`}
    >
      {/* 
          1. h-screen: makes the body exactly the height of the window.
          2. flex-col: stacks Navbar and Main vertically.
      */}
      <body className="antialiased h-screen flex overflow-hidden">
        {/* The Header (Fixed height) */}
        <Navbar />
        {/* 
            The Body/Main Content 
            1. flex-1: tells this container to grow and take up all remaining space.
            2. overflow-y-auto: allows only the content area to scroll, keeping the header fixed at the top.
        */}
        <main className="flex-1 overflow-y-auto bg-gray-50">{children}</main>
      </body>
    </html>
  );
}
